export enum EntityType {
    NONE = 'none',
    BRICK_WALL = 'brick-wall',
    STEEL_WALL = 'steel-wall',
    BUSH = 'bush',
    PLAYER_SPAWN = 'player-spawn',
    LEVEL_BORDER = 'level-border',
    TANK = 'tank',
    BULLET = 'bullet',
    EXPLOSION = 'explosion',
    ICE = 'ice',
    SMOKE = 'smoke',
    WATER = 'water',
    SAND = 'sand',
    GRASS = 'grass',
    DIRT = 'dirt',
    FLAG = 'flag',
    FLAG_BASE = 'flag-base',
    TELEPORTER = 'teleporter',
    SPAWN_EFFECT = 'spawn-effect',
    PLAYER = 'player',
    TEAM = 'team',
    GAME_MODE = 'game-mode',
    TIME = 'time',
}
